### ISSUE TITLE
미니 프로젝트 주제 정하기

### ISSUE THREAD

**Issue by oldprize47** [greenyeast/23-OSS-airline-ticket#1]
저희 주제를 슬슬 정해야 할 것 같은데 혹시 각자 괜찮을 것 같은 주제 2개씩만 골라서 적을까요?

**Comment by GayoungKim060** [comment]
저는 1. Message 서비스 
-Create: 메시지 생성
-Read: 받은/보낸 메시지 읽기
-Update: 메시지 수정
-Delete: 메시지 삭제
2.Airplane 예매 시스템 
-Create: 예매받을 비행기표 시간 생성
-Read: 예매가능한 비행기표 목록 읽기 
-Update: 예매 비행기표 시간 변경
-Delete: 비행기표 시간 삭제/예매 비행기표 삭제

요정도 생각했습니다~! 세부적인 내용은 더 많을 것같은데 대표적인 것만 작성해봤어요 관심있으신거 있으면 더 develop해서 해도 또 좋은 아이디어 있으면 의논해봐요😄

**Comment by oldprize47** [comment]
그럼 저는
1. 온라인 서점 - 관리자 용
-Create: 도서 추가
-Read: 현재 도서 목록
-Update: 도서 정보 수정
-Delete: 도서 삭제
(그 외 메뉴)  - 이용자 용
도서 구매 서비스 - 책 구매하기
평점 입력 - 구매한 도서의 평점을 입력할 수 있도록 함.
베스트 셀러 - 누적된 평점의 평균을 계산해서 상위 10권 표시

-> 혹시나 로그인을 할 수 있도록 만든다면 괜찮을 수도 있을 것 같아요. 관리자나 이용자의 id, pw를 txt파일에 저장해서 비교하는것 처럼요. 

그리고 Airplane 예매 시스템도 괜찮아 보여요 비슷하게 고객용, 관리자 용으로 한다면 할 수 있는 메뉴가 굉장히 많아질 것 같아요~! ex) 관리자 - 비행기 시간, 총 좌석 등록, 현재 등록한 비행기 목록, 비행기 정보 업데이트, 비행 편 삭제
 이용자 - 비행기 표 끊기 (이용자 정보 입력), 현재 예매한 표 확인, 예매 정보 변경, 예매 취소 이런식으로 가도 좋을 것 같아요!

**Comment by oldprize47** [comment]
아 아니면 과제 공지로 올라온 
CAFE 디저트 자판기도 괜찮을 것 같다는 생각이 들어요
-Create: 메뉴 추가
-Read: 현재 메뉴 목록
-Update: 메뉴 정보 수정
-Delete: 메뉴 삭제

(그 외 메뉴) - 이용자 용
장바구니 확인, 장바구니 담기, 계산하기, 현재 대기 인원 표시 등등..?

한번 어떤게 적절할지 얘기해 보면 좋을 것 같아요~!!

**Comment by greenyeast** [comment]
-> 로그인 기능 추가하는 것도 좋을것 같아요!!
-> 저도 공지 주제 신선하다고 생각했어요! 그런데 뭔가 프로젝트 주제는 새로운 데이터를 다뤄보는게 좋을것 같아요
-> 그래서 온라인 서점도 굉장히 좋을 것같아요! 그런데 뭔가 온라인 서점은 학교안에서 금방 접할 수 있는 주제같아서 다른 팀에서 했을것 같기도 하고 겹칠것 같아서.. 주제는 비행기로 가는건 어떠신가요? 생각한 기능들은 충분히 주제 안에 녹여 낼 수 있을것 같아서요, 예를 들어 평점 입력도 비행사에 따라서 매길수 있고 회원로그인도 충분히 구현  할 수 있을 것 같아요 😃

**Comment by oldprize47** [comment]
너무 좋아요~~!! 그럼 주제는 비행기로 해봐요

**Comment by greenyeast** [comment]
좋아요😃 주제 선정 이슈는 close하고 기능 논의해봐요~!!
