### ISSUE TITLE
프로젝트 역할 분담

### ISSUE THREAD

**Issue by oldprize47** [greenyeast/23-OSS-airline-ticket#3]
이제 역할 분담을 정해야 할 것 같은데 더 필요한 역할이 있을 것 같으면 편하게 적어주세요!!

- CRUD 구현
- 부가기능 구현
- WIKI 관리
- 코드 관리 (오류수정)

**Comment by greenyeast** [comment]
좋아요! CRUD 기능 개발, 부가기능 구현 개발 을 절반씩 할당하고 WIKI, 코드 관리는 같이 의논해서 develop해나가는 방식으로 가는건 어떨까요?😀 개발할 기능들이 많을것 같긴하지만.. 하항...
