### ISSUE TITLE
프로젝트 구조 정의

### ISSUE THREAD

**Issue by greenyeast** [greenyeast/23-OSS-airline-ticket#4]
# 비행기 표와 정보에 들어갈 내용

##### 비행기 정보
- 목적지,
- 출발 시간
- 좌석 수
- 비행기 이름

##### 비행기 표 
- 출발시간
- 탑승 게이트
- 좌석 번호
- 비행기 이름

##### 회원정보
- 회원이름
- id
- pw

### 구조체 데이터 종류
문자열 - 목적지, 비행기 이름, 탑승객 이름, 아이디, 패스워드, 비행기 좌석 번호
정수 - 탑승 게이트, 출발 시간, 좌석 수, 남은 좌석 수

**Comment by greenyeast** [comment]
```c
typedef struct{
    char userId[100];
    
}Ticket;
```

```c
typedef struct{
    char 
}User;
```

**Comment by oldprize47** [comment]
공통
현재 등록된 비행기 목록 확인
회원가입 & 로그인

관리자
항공편 생성
항공편 정보 변경
항공편 삭제

이용자
티켓 예매
예매 정보 변경
예매 취소
이용했던 항공사 평점 부여
목적지 검색시 가격 비교 목록
항공사 랭킹 별 목록 확인

**Comment by oldprize47** [comment]
Create
예매 받을 비행기표 시간 생성 (admin)
비행기 좌석 등록 (admin)
예매 사용자 생성 (user)
Read
현재 등록한 비행기 목록 (admin)
예매가능한 비행기표 목록 (user)
예매 항공권 목록 (user)
Update
예매 비행기표 시간 변경
예매 정보 변경 (user/admin)
Delete
비행기표 시간 삭제/예매 비행기표 삭제
예매 비행기표 삭제 (admin)
데이터 파일 저장
회원 데이터
그외 검색 메뉴
목적지에 따른 비행기 목록 검색
